[book]
authors = ["Jonas da Silva"]
language = "en"
multilingual = false
src = "src"
title = "Allay Manual"

[output.html]
additional-css = [
  "theme/whichlang.css",
  "theme/custom.css",
  "theme/nord.css",
  "theme/nord-alerts.css",
  "theme/nord-highlight.css",
]
additional-js = ["scripts/whichlang.js"]
default-theme = "snow-storm"
preferred-dark-theme = "polar-night"
smart-punctuation = true
git-repository-url = "https://github.com/allay-mc/allay"
no-section-label = true

[build]
build-dir = "../target/manual"

[preprocessor.alerts]

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
