Source config.tape
Require allay
Output create.gif

Hide
Type "cd /tmp"
Enter
Type "rm -rf my_furniture"
Enter
Show

Type "allay create"
Enter
Sleep 800ms

Type "My Furniture"
Enter
Sleep 800ms

Type "Furniture and Decoration for your House!"
Enter
Sleep 800ms

Enter
Sleep 800ms

Enter
Sleep 800ms

Enter
Sleep 800ms

Enter
Sleep 800ms

Enter
Sleep 800ms

Enter
Sleep 800ms

Enter
Sleep 800ms

Type "cd my_furniture"
Enter
Sleep 800ms

Type "touch src/BP/content.yaml"
Enter
Sleep 800ms

Type "allay build"
Enter
Sleep 2s
