{# using tera #}[project.name]
{{ project_primary_language }} = "{{ project_name }}"

[project.description]
{%- if project_description %}
{{ project_primary_language }} = "{{ project_description }}"
{%- endif %}

[project]
version = "{{ project_version }}"
license = "{{ project_license }}"
min-engine-version = "{{ project_min_engine_version }}"

[localization]
primary-language = "{{ project_primary_language }}"

[build]
extra-watch = ["plugins"]

